Repository 2-frame/2-frame, pull requests merged in 2025-01, with the labels that each got.

#4 [BE] 초기 프로젝트 설정 및 베이스 코드 작성
  .gitignore
  server/.gitattributes
  server/.gitignore
  server/.springjavaformatconfig
  server/build.gradle
  server/gradle.properties
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/lint.gradle
  server/settings.gradle
  server/src/main/java/com/frame2/server/ServerApplication.java
  server/src/main/java/com/frame2/server/core/example/api/ExampleApi.java
  server/src/main/java/com/frame2/server/core/example/application/ExampleService.java
  server/src/main/java/com/frame2/server/core/example/application/ExampleServiceImpl.java
  server/src/main/java/com/frame2/server/core/example/domain/Example.java
  server/src/main/java/com/frame2/server/core/example/infrastructure/ExampleCalculateRule.java
  server/src/main/java/com/frame2/server/core/example/infrastructure/ExampleExternalClient.java
  server/src/main/java/com/frame2/server/core/example/infrastructure/ExampleRepository.java
  server/src/main/java/com/frame2/server/core/example/payload/ExampleRegisterRequest.java
  server/src/main/java/com/frame2/server/core/example/payload/ExampleSearchResponse.java
  server/src/main/java/com/frame2/server/core/example/payload/SimpleExample.java
  server/src/main/java/com/frame2/server/core/support/entity/BaseEntity.java
  server/src/main/java/com/frame2/server/core/support/exception/ApiExceptionAdvice.java
  server/src/main/java/com/frame2/server/core/support/exception/DomainException.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionCode.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionResponse.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionType.java
  server/src/main/java/com/frame2/server/core/support/response/IdResponse.java
  server/src/main/java/com/frame2/server/global/config/AsyncConfig.java
  server/src/main/java/com/frame2/server/global/config/AsyncExceptionHandler.java
  server/src/main/resources/application-local-dev.yml
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
  server/src/main/resources/logback/logback-local-dev.xml
  server/src/main/resources/logback/logback-local.xml
  server/src/main/resources/logging.yml
  server/src/test/java/com/frame2/server/ServerApplicationTests.java
Labels: ✨ BE, 우선순위:상

#13 feat: 회원가입 기능 구현
  server/build.gradle
  server/src/main/java/com/frame2/server/core/example/api/ExampleApi.java
  server/src/main/java/com/frame2/server/core/example/api/ExampleApiSpec.java
  server/src/main/java/com/frame2/server/core/member/application/MemberService.java
  server/src/main/java/com/frame2/server/core/member/application/MemberServiceImpl.java
  server/src/main/java/com/frame2/server/core/member/domain/AccountStatus.java
  server/src/main/java/com/frame2/server/core/member/domain/BasicAuthentication.java
  server/src/main/java/com/frame2/server/core/member/domain/Member.java
  server/src/main/java/com/frame2/server/core/member/infrastructure/BasicAuthenticationRepository.java
  server/src/main/java/com/frame2/server/core/member/infrastructure/MemberRepository.java
  server/src/main/java/com/frame2/server/core/member/payload/SignupInfo.java
  server/src/main/java/com/frame2/server/core/member/payload/request/SignupRequest.java
  server/src/main/java/com/frame2/server/core/support/entity/BaseEntity.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionCode.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionType.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
  server/src/test/java/com/frame2/server/core/member/application/MemberServiceImplTest.java
  server/src/test/resources/application.yml
Labels: 🍰 초간단

#14 [All]2-frame 컨벤션 md파일 추가
  README.md
Labels: 💭 고민거리, 📋 문서

#16 [BE] feat: 인가 기능 및 내 정보 조회 기능 구현
  server/src/main/java/com/frame2/server/core/member/api/AuthAPI.java
  server/src/main/java/com/frame2/server/core/member/api/AuthAPISpec.java
  server/src/main/java/com/frame2/server/core/member/api/MemberAPI.java
  server/src/main/java/com/frame2/server/core/member/api/MemberAPISpec.java
  server/src/main/java/com/frame2/server/core/member/application/MemberService.java
  server/src/main/java/com/frame2/server/core/member/application/MemberServiceImpl.java
  server/src/main/java/com/frame2/server/core/member/payload/response/MyInformationResponse.java
  server/src/main/java/com/frame2/server/core/support/annotations/Auth.java
  server/src/main/java/com/frame2/server/core/support/annotations/MemberOnly.java
  server/src/main/java/com/frame2/server/core/support/exception/ApiExceptionAdvice.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionCode.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionType.java
  server/src/main/java/com/frame2/server/core/support/handler/MemberOnlyHandler.java
  server/src/main/java/com/frame2/server/core/support/request/User.java
  server/src/main/java/com/frame2/server/core/support/resolver/ArgumentResolverConfig.java
  server/src/main/java/com/frame2/server/core/support/resolver/SignInArgumentResolver.java
Labels: 🚀 기능

#17 [All] ERD 마이그레이션 및 수정
  README.md
  img/frame2_20250115.drawio.png
Labels: 📋 문서

#18 [BE] docs: 프로젝트 요구사항 정리
  docs/Board.md
  docs/CartItem.md
  docs/MemberAndAuth.md
  docs/Order.md
  docs/Product.md
  docs/index.md
  pull-request-template.md
Labels: ✨ BE, 📋 문서

#39 [BE] feat: BaseEntity 컬럼 1개 추가
  server/src/main/java/com/frame2/server/core/support/entity/BaseEntity.java
Labels: ✨ BE

#42 [BE] 회원 계정 잠금 기능 구현
  server/src/main/java/com/frame2/server/core/member/application/MemberServiceImpl.java
  server/src/main/java/com/frame2/server/core/member/domain/BasicAuthentication.java
  server/src/main/java/com/frame2/server/core/member/domain/LoginStatus.java
  server/src/main/java/com/frame2/server/core/member/domain/Member.java
  server/src/main/java/com/frame2/server/core/member/domain/MemberCredential.java
  server/src/main/java/com/frame2/server/core/member/infrastructure/BasicAuthenticationRepository.java
  server/src/main/java/com/frame2/server/core/member/infrastructure/MemberCredentialRepository.java
  server/src/main/java/com/frame2/server/core/member/payload/request/SignupRequest.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionCode.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionType.java
  server/src/test/java/com/frame2/server/core/member/application/MemberServiceImplTest.java
  server/src/test/java/com/frame2/server/core/member/domain/BasicAuthenticationTest.java
  server/src/test/java/com/frame2/server/core/member/domain/MemberCredentialTest.java
  server/src/test/java/com/frame2/server/fixture/BasicAuthenticationFixture.java
  server/src/test/java/com/frame2/server/fixture/MemberCredentialFixture.java
Labels: ✨ BE

#46 [BE] refactor: OSIV 설정 추가
  server/src/main/resources/application-local-dev.yml
  server/src/main/resources/application-local.yml
Labels: ✨ BE

#56 [BE] refactor: 장바구니 상품 조회 기능 - 코드 리뷰 반영 6차
  server/src/main/java/com/frame2/server/core/cart/api/CartApiSpec.java
Labels: ✨ BE

#60 [BE] feat: 장바구니 상품 추가 기능 구현
  docs/CartItem.md
  server/src/main/java/com/frame2/server/core/cart/api/CartApi.java
  server/src/main/java/com/frame2/server/core/cart/api/CartApiSpec.java
  server/src/main/java/com/frame2/server/core/cart/application/CartService.java
  server/src/main/java/com/frame2/server/core/cart/application/CartServiceImpl.java
  server/src/main/java/com/frame2/server/core/cart/payload/request/CartItemRequest.java
  server/src/main/java/com/frame2/server/core/product/infrastructure/SaleProductRepository.java
Labels: ✨ BE

#55 [BE] feat: 주문 / 주문 상세 생성 기능
  server/src/main/java/com/frame2/server/core/order/api/OrderApi.java
  server/src/main/java/com/frame2/server/core/order/api/OrderApiSpec.java
  server/src/main/java/com/frame2/server/core/order/application/OrderService.java
  server/src/main/java/com/frame2/server/core/order/application/OrderServiceImpl.java
  server/src/main/java/com/frame2/server/core/order/domain/DeliveryStatus.java
  server/src/main/java/com/frame2/server/core/order/domain/Order.java
  server/src/main/java/com/frame2/server/core/order/domain/OrderDetail.java
  server/src/main/java/com/frame2/server/core/order/domain/OrderStatus.java
  server/src/main/java/com/frame2/server/core/order/infrastructure/OrderDetailRepository.java
  server/src/main/java/com/frame2/server/core/order/infrastructure/OrderRepository.java
  server/src/main/java/com/frame2/server/core/order/payload/request/OrderCreateRequest.java
Labels: ✨ BE

#61 [BE] feat: 장바구니 상품 수량 자동 증가 구현
  docs/CartItem.md
  server/src/main/java/com/frame2/server/core/cart/application/CartServiceImpl.java
  server/src/main/java/com/frame2/server/core/cart/domain/CartItem.java
  server/src/main/java/com/frame2/server/core/cart/infrastructure/CartItemRepository.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionCode.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#58 [BE] feat: 인증 코드 발신 기능 추가
  server/src/main/java/com/frame2/server/core/member/application/MemberEmailService.java
  server/src/main/java/com/frame2/server/core/member/application/MemberServiceImpl.java
  server/src/main/java/com/frame2/server/core/member/domain/EmailVerificationCode.java
  server/src/main/java/com/frame2/server/core/member/domain/RandomGenerator.java
  server/src/main/java/com/frame2/server/core/member/infrastructure/AuthenticationCodeGenerator.java
  server/src/main/java/com/frame2/server/core/member/infrastructure/EmailVerificationCodeRepository.java
  server/src/test/java/com/frame2/server/core/mail/application/FakeEmailClient.java
Labels: ✨ BE

#62 feat: 주문에 총 금액, 대표 상품명 생성 기능 구현
  server/src/main/java/com/frame2/server/core/order/application/OrderServiceImpl.java
  server/src/main/java/com/frame2/server/core/order/domain/Order.java
Labels: ✨ BE

#66 [BE] 카테고리별 조회 및 카테고리별 상품 조회 기능 구현
  server/src/main/java/com/frame2/server/core/product/api/CategoryApi.java
  server/src/main/java/com/frame2/server/core/product/api/CategoryApiSpec.java
  server/src/main/java/com/frame2/server/core/product/api/ProductApiSpec.java
  server/src/main/java/com/frame2/server/core/product/application/CategoryService.java
  server/src/main/java/com/frame2/server/core/product/application/CategoryServiceImpl.java
  server/src/main/java/com/frame2/server/core/product/application/ProductService.java
  server/src/main/java/com/frame2/server/core/product/application/ProductServiceImpl.java
  server/src/main/java/com/frame2/server/core/product/infrastructure/CategoryRepository.java
  server/src/main/java/com/frame2/server/core/product/infrastructure/ProductRepository.java
  server/src/main/java/com/frame2/server/core/product/payload/response/CategoryResponse.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionCode.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionType.java
Labels: 🚀 기능

#72 [AI] feat: chatbot 서비스 1차 개발완료
  chatbot/chatbot.py
  chatbot/main.py
  chatbot/models.py
  chatbot/requirements.txt
  chatbot/templates/index.html
Labels: 🤖 AI

#74 [BE] feat: 주문 / 주문 상세 내역 조회 기능 구현
  server/src/main/java/com/frame2/server/core/order/api/OrderApi.java
  server/src/main/java/com/frame2/server/core/order/api/OrderApiSpec.java
  server/src/main/java/com/frame2/server/core/order/application/OrderService.java
  server/src/main/java/com/frame2/server/core/order/application/OrderServiceImpl.java
  server/src/main/java/com/frame2/server/core/order/domain/OrderDetail.java
  server/src/main/java/com/frame2/server/core/order/infrastructure/OrderDetailRepository.java
  server/src/main/java/com/frame2/server/core/order/infrastructure/OrderRepository.java
  server/src/main/java/com/frame2/server/core/order/payload/request/OrderCreateRequest.java
  server/src/main/java/com/frame2/server/core/order/payload/response/OrderDetailResponse.java
  server/src/main/java/com/frame2/server/core/order/payload/response/OrderResponse.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionCode.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#47 [Be] feat:5 상품 QnA 기능 구현
  server/src/main/java/com/frame2/server/core/board/api/ProductQnAApi.java
  server/src/main/java/com/frame2/server/core/board/api/ProductQnAApiSpec.java
  server/src/main/java/com/frame2/server/core/board/application/ProductQnAServiceImpl.java
  server/src/main/java/com/frame2/server/core/board/application/ProductQnAdService.java
  server/src/main/java/com/frame2/server/core/board/domain/AnswerStatus.java
  server/src/main/java/com/frame2/server/core/board/domain/ProductQnA.java
  server/src/main/java/com/frame2/server/core/board/infrastructure/ProductQnARepository.java
  server/src/main/java/com/frame2/server/core/board/payload/SimpleProductQnA.java
  server/src/main/java/com/frame2/server/core/board/payload/request/ProductQnAAnswerRequest.java
  server/src/main/java/com/frame2/server/core/board/payload/request/ProductQnAModifyRequest.java
  server/src/main/java/com/frame2/server/core/board/payload/request/ProductQnARegisterRequest.java
  server/src/main/java/com/frame2/server/core/board/payload/response/ProductQnAListResponse.java
  server/src/main/java/com/frame2/server/core/board/payload/response/ProductQnAResponse.java
  server/src/main/java/com/frame2/server/core/support/entity/BaseEntity.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionCode.java
  server/src/main/java/com/frame2/server/core/support/exception/ExceptionType.java
  server/src/test/java/com/frame2/server/core/board/application/ProductQnAServiceImplTest.java
Labels: ✨ BE

#78 [BE] feat: 장바구니 상품 삭제 기능 구현
  docs/CartItem.md
  server/src/main/java/com/frame2/server/core/cart/api/CartApi.java
  server/src/main/java/com/frame2/server/core/cart/api/CartApiSpec.java
  server/src/main/java/com/frame2/server/core/cart/application/CartService.java
  server/src/main/java/com/frame2/server/core/cart/application/CartServiceImpl.java
  server/src/main/java/com/frame2/server/core/support/entity/BaseEntity.java
Labels: ✨ BE

#98 [BE]refactor: Category엔티티의 product 컬럼 삭제
  server/src/main/java/com/frame2/server/core/product/domain/Category.java
Labels: ✨ BE

#105 [BE] feat: Option 크롤링
  crawler/.gitignore
  crawler/build.gradle
  crawler/secret/application-local-dev.yml
  crawler/secret/application.properties
  crawler/settings.gradle
  crawler/src/main/java/com/frame2/crawler/api/CrawlerApi.java
  crawler/src/main/java/com/frame2/crawler/application/CrawlerService.java
  crawler/src/main/java/com/frame2/crawler/infrastructure/OptionRepository.java
Labels: ✨ BE

#90 [BE] feat: 주문 전체 취소/부분 취소 및 재고 가산 기능 구현
  server/src/main/java/com/frame2/server/core/order/api/OrderApi.java
  server/src/main/java/com/frame2/server/core/order/api/OrderApiSpec.java
  server/src/main/java/com/frame2/server/core/order/application/OrderService.java
  server/src/main/java/com/frame2/server/core/order/application/OrderServiceImpl.java
  server/src/main/java/com/frame2/server/core/order/domain/Order.java
  server/src/main/java/com/frame2/server/core/order/domain/OrderDetail.java
  server/src/main/java/com/frame2/server/core/order/domain/OrderStatus.java
  server/src/main/java/com/frame2/server/core/order/infrastructure/OrderDetailRepository.java
  server/src/main/java/com/frame2/server/core/order/infrastructure/OrderRepository.java
  server/src/main/java/com/frame2/server/core/product/domain/Stock.java
Labels: ✨ BE

#111 [BE] feat: Category 데이터 생성
  crawler/src/main/java/com/frame2/crawler/api/CrawlerApi.java
  crawler/src/main/java/com/frame2/crawler/application/CrawlerService.java
  crawler/src/main/java/com/frame2/crawler/domain/Category.java
Labels: ✨ BE

#115 [BE] feat: 주문 기능에 @Auth, User 추가
  server/src/main/java/com/frame2/server/core/board/application/ProductReviewServiceImpl.java
  server/src/main/java/com/frame2/server/core/order/api/OrderApi.java
  server/src/main/java/com/frame2/server/core/order/api/OrderApiSpec.java
  server/src/main/java/com/frame2/server/core/order/application/OrderService.java
  server/src/main/java/com/frame2/server/core/order/application/OrderServiceImpl.java
  server/src/main/java/com/frame2/server/core/order/infrastructure/OrderDetailRepository.java
  server/src/main/java/com/frame2/server/core/order/infrastructure/OrderRepository.java
  server/src/main/java/com/frame2/server/core/order/payload/request/OrderCreateRequest.java
Labels: ✨ BE

#86 [Be]refactor: 85 상품 QnA 수정
  server/src/main/java/com/frame2/server/core/board/api/ProductQnAApi.java
  server/src/main/java/com/frame2/server/core/board/api/ProductQnAApiSpec.java
  server/src/main/java/com/frame2/server/core/board/application/ProductQnAServiceImpl.java
  server/src/main/java/com/frame2/server/core/board/application/ProductQnAdService.java
  server/src/main/java/com/frame2/server/core/board/domain/AnswerStatus.java
  server/src/main/java/com/frame2/server/core/board/domain/ProductQnA.java
  server/src/main/java/com/frame2/server/core/board/infrastructure/ProductQnARepository.java
  server/src/main/java/com/frame2/server/core/board/payload/SimpleProductQnA.java
  server/src/main/java/com/frame2/server/core/board/payload/request/ProductQnAAnswerRequest.java
  server/src/main/java/com/frame2/server/core/board/payload/request/ProductQnAModifyRequest.java
  server/src/main/java/com/frame2/server/core/board/payload/request/ProductQnARegisterRequest.java
  server/src/test/java/com/frame2/server/core/board/application/ProductQnAServiceImplTest.java
Labels: 🍰 초간단
